packages:
  - packages/*
  - libs/*
  - apps/*

patchedDependencies:
  electron-vite: patches/electron-vite.patch

catalog:
  '@xsai-ext/providers-cloud': ^0.3.5
  '@xsai-ext/providers-local': ^0.3.5
  '@xsai/embed': ^0.3.5

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - bufferutil
  - electron
  - electron-winstaller
  - es5-ext
  - esbuild
  - sharp
  - unrs-resolver
  - utf-8-validate
  - vue-demi
  - websocket
